# Generated by Django 3.0.2 on 2020-01-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=8)),
                ('description', models.TextField(max_length=1000)),
                ('discount', models.FloatField()),
            ],
        ),
    ]
